# Generated by Django 2.1.2 on 2019-05-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='title',
            field=models.CharField(max_length=80, verbose_name='标题'),
        ),
    ]
